# Generated by Django 4.2.3 on 2024-04-21 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0002_parking_num_spaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='vacancy_type',
            field=models.CharField(choices=[('conventional', 'Conventional'), ('priority', 'Priority')], default='conventional', max_length=13),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.parkingspace')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.ticket')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
