# Generated by Django 4.2.3 on 2024-04-21 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_parkingspace_vacancy_type_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.ticket'),
        ),
    ]
